"""GENERATED by freertos/cvitek/task/balance_car/tools/gen_bc_layout.py - do not edit."""
import struct

SHM_PHYS = 0x9FFF0000
SHM_SIZE = 0x10000
SHM_MAGIC = 0x4D534342
SHM_VERSION = 1

# offsets inside the window
OFF_HDR, OFF_STATUS, OFF_LINUX = 0x0000, 0x0040, 0x0080
OFF_PARAM, OFF_ECHO, OFF_CALIB = 0x0100, 0x0500, 0x0600
OFF_TELEM, OFF_EVENTS = 0x0800, 0x4800
TELEM_SLOTS, EVENT_SLOTS = 256, 128

HDR_FMT = '<4I16s8I'
STATUS_FIELDS = ('rtos_heartbeat', 'state', 'fault', 'deadline_miss', 'imu_err', 'cpu_load_pct',
                 'telem_head', 'event_head', 'cycles', 'lost_cmds', 'stack_min0', 'stack_min1',
                 'stack_min2', 'stack_min3', 'imu_variant', 'reserved0')
STATUS_FMT = '<16I'
CALIB_FIELDS = ('seq', 'valid', 'gyro_bias_x', 'gyro_bias_y', 'gyro_bias_z', 'accel_x', 'accel_y',
                'accel_z', 'trim_deg', 'temp_c')
CALIB_FMT = '<2I8f'            # followed by 8 reserved words
LINUX_FMT = '<16I'
TELEM_FIELDS = ('seq', 't_us', 'pitch_cdeg', 'pitch_acc_cdeg', 'gyro_y_cdps', 'gyro_z_cdps',
                'accel_norm_mg', 'speed_l_mmps', 'speed_r_mmps', 'angle_set_cdeg', 'motor_l_pm',
                'motor_r_pm', 'target_speed_mmps', 'target_turn_mradps', 'enc_l', 'enc_r',
                'vbat_mv', 'exec_us', 'period_us', 'state', 'fault', 'imu_err', 'flags', 'psi_mrad', 'x_mm', 'pad', 'crc')
TELEM_FMT = '<II12hiiHHHBBBBhi4sI'
EVENT_FIELDS = ('seq', 't_us', 'type', 'arg', 'val', 'pad')
EVENT_FMT = '<IIHHi16s'

# parameter set: (name, type, default, min, max); order == C struct order
PARAMS = (
    ('est_alpha', 'F', 0.998, 0.9, 0.9999),
    ('est_gate_g', 'F', 0.1, 0.0, 1.0),
    ('est_bias_gain', 'F', 0.02, 0.0, 1.0),
    ('est_mode', 'I', 0, 0, 1),
    ('est_spike_deg', 'F', 20.0, 0.0, 90.0),
    ('kf_q_angle', 'F', 0.001, 1e-06, 1.0),
    ('kf_q_bias', 'F', 0.003, 1e-06, 1.0),
    ('kf_r', 'F', 3.0, 0.0001, 10.0),
    ('kf_robust_deg', 'F', 3.0, 0.0, 30.0),
    ('a_kp', 'F', 15.0, 3.5, 60.0),
    ('a_kd', 'F', 0.8, 0.0, 5.0),
    ('a_ki', 'F', 0.0, 0.0, 5.0),
    ('trim_deg', 'F', 0.0, -15.0, 15.0),
    ('a_out_max', 'F', 90.0, 20.0, 100.0),
    ('v_kp', 'F', 1.94, 0.0, 8.0),
    ('v_ki', 'F', 1.94, 0.0, 8.0),
    ('v_max_deg', 'F', 8.0, 0.0, 20.0),
    ('v_filter', 'F', 0.3, 0.01, 1.0),
    ('x_kp', 'F', 0.0, 0.0, 3.0),
    ('x_vmax', 'F', 0.15, 0.02, 1.0),
    ('t_kp', 'F', 5.0, 0.0, 30.0),
    ('t_ki', 'F', 5.0, 0.0, 30.0),
    ('t_max', 'F', 20.0, 0.0, 50.0),
    ('t_speed_scale', 'F', 0.5, 0.05, 5.0),
    ('deadband_pct', 'F', 6.0, 0.0, 20.0),
    ('motor_max_pct', 'F', 90.0, 20.0, 100.0),
    ('acc_max', 'F', 0.5, 0.05, 5.0),
    ('alpha_max', 'F', 3.0, 0.1, 20.0),
    ('v_max', 'F', 0.5, 0.0, 2.0),
    ('w_max', 'F', 2.0, 0.0, 6.0),
    ('fall_deg', 'F', 45.0, 20.0, 80.0),
    ('lift_speed_mps', 'F', 1.5, 0.3, 5.0),
    ('sat_ms', 'F', 300.0, 50.0, 5000.0),
    ('cmd_timeout_ms', 'F', 500.0, 100.0, 10000.0),
    ('hb_disarm_ms', 'F', 0.0, 0.0, 600000.0),
    ('wheel_diam_m', 'F', 0.065, 0.02, 0.3),
    ('track_m', 'F', 0.17, 0.05, 0.6),
    ('enc_cpr', 'F', 3960.0, 100.0, 100000.0),
    ('imu_sign', 'S', 1, -1, 1),
    ('motor_sign_l', 'S', 1, -1, 1),
    ('motor_sign_r', 'S', 1, -1, 1),
    ('enc_sign_l', 'S', 1, -1, 1),
    ('enc_sign_r', 'S', 1, -1, 1),
)
PARAM_FMT = '<' + ''.join('f' if p[1] == 'F' else 'i' for p in PARAMS)
PARAM_COUNT = len(PARAMS)
PARAM_BLK_FMT = '<4I' + PARAM_FMT[1:]      # seq, crc, version, size, params
ECHO_FMT = '<4I' + PARAM_FMT[1:]           # seq, applied_count, last_result, applied_seq, params

assert struct.calcsize(HDR_FMT) == 64
assert struct.calcsize(STATUS_FMT) == 64
assert struct.calcsize(TELEM_FMT) == 64
assert struct.calcsize(EVENT_FMT) == 32

# event-ring types (BC_EVT_LOG_*)
EVT_LOG_STATE, EVT_LOG_CMD, EVT_LOG_PARAMS, EVT_LOG_CALIB, EVT_LOG_TIMING, EVT_LOG_PONG = 1, 2, 3, 4, 5, 6

# mailbox protocol (bc_proto.h)
BC_IP_ID = 8
BC_CMD_PING = 0x01
BC_CMD_ARM = 0x02
BC_CMD_DISARM = 0x03
BC_CMD_SET_TARGET = 0x04
BC_CMD_APPLY_PARAMS = 0x05
BC_CMD_HEARTBEAT = 0x06
BC_CMD_CALIBRATE = 0x07
BC_CMD_ESTOP = 0x08
BC_EVT_STATE = 0x40
BC_EVT_PONG = 0x41
BC_EVT_PARAMS_ACK = 0x42
BC_EVT_CALIB_DONE = 0x43
BC_EVT_HEARTBEAT = 0x44
BC_EVT_FAULT = 0x45
BC_CALIB_GYRO = 1
BC_CALIB_TRIM = 2

STATE_NAMES = ('BOOT', 'CALIBRATING', 'IDLE', 'ARMING', 'BALANCING', 'FALLEN', 'FAULT', 'ESTOP')
FAULT_NAMES = ('NONE', 'FALL', 'LIFT', 'IMU_BUS', 'IMU_STUCK', 'IMU_RANGE', 'SATURATION', 'TIMING',
               'ESTOP', 'PARAM', 'IMU_INIT', 'CALIB')
