#!/usr/bin/env python3
"""Generate the Linux-side mirror of the RTOS shared-memory/parameter layout.

Input : include/bc_params.h (X-macro parameter list), include/bc_proto.h (ids)
Output: device/generic/rootfs_overlay/duos/mnt/system/bc/bc_layout.py

CI regenerates the file and fails if it differs from the checked-in copy, and
test/layout_dump.c cross-checks every offset against the C compiler's view.
"""
import re
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
INC = HERE.parent / "include"
OUT = HERE.parents[4] / "device/generic/rootfs_overlay/duos/mnt/system/bc/bc_layout.py"


def parse_params():
    text = (INC / "bc_params.h").read_text()
    block = text[text.index("#define BC_PARAM_LIST"):text.index("typedef struct {")]
    out = []
    for m in re.finditer(r"X\((\w+),\s*([FIS]),\s*([-\d.eE+f]+),\s*([-\d.eE+f]+),\s*([-\d.eE+f]+)\)", block):
        name, typ, d, lo, hi = m.groups()
        conv = (lambda v: float(v.rstrip("f"))) if typ == "F" else (lambda v: int(float(v.rstrip("f"))))
        out.append((name, typ, conv(d), conv(lo), conv(hi)))
    if not out:
        sys.exit("no parameters parsed")
    return out


def parse_proto():
    text = (INC / "bc_proto.h").read_text()
    return re.findall(r"#define\s+(BC_(?:CMD|EVT|CALIB|IP)_\w+)\s+(0x[0-9A-Fa-f]+|\d+)", text)


def main():
    params = parse_params()
    proto = parse_proto()
    lines = [
        '"""GENERATED by freertos/cvitek/task/balance_car/tools/gen_bc_layout.py - do not edit."""',
        "import struct",
        "",
        "SHM_PHYS = 0x9FFF0000",
        "SHM_SIZE = 0x10000",
        "SHM_MAGIC = 0x4D534342",
        "SHM_VERSION = 1",
        "",
        "# offsets inside the window",
        "OFF_HDR, OFF_STATUS, OFF_LINUX = 0x0000, 0x0040, 0x0080",
        "OFF_PARAM, OFF_ECHO, OFF_CALIB = 0x0100, 0x0500, 0x0600",
        "OFF_TELEM, OFF_EVENTS = 0x0800, 0x4800",
        "TELEM_SLOTS, EVENT_SLOTS = 256, 128",
        "",
        "HDR_FMT = '<4I16s8I'",
        "STATUS_FIELDS = ('rtos_heartbeat', 'state', 'fault', 'deadline_miss', 'imu_err', 'cpu_load_pct',",
        "                 'telem_head', 'event_head', 'cycles', 'lost_cmds', 'stack_min0', 'stack_min1',",
        "                 'stack_min2', 'stack_min3', 'reserved0', 'reserved1')",
        "STATUS_FMT = '<16I'",
        "LINUX_FMT = '<16I'",
        "TELEM_FIELDS = ('seq', 't_us', 'pitch_cdeg', 'pitch_acc_cdeg', 'gyro_y_cdps', 'gyro_z_cdps',",
        "                'accel_norm_mg', 'speed_l_mmps', 'speed_r_mmps', 'angle_set_cdeg', 'motor_l_pm',",
        "                'motor_r_pm', 'target_speed_mmps', 'target_turn_mradps', 'enc_l', 'enc_r',",
        "                'vbat_mv', 'exec_us', 'period_us', 'state', 'fault', 'imu_err', 'flags', 'pad', 'crc')",
        "TELEM_FMT = '<II12hiiHHHBBBB10sI'",
        "EVENT_FIELDS = ('seq', 't_us', 'type', 'arg', 'val', 'pad')",
        "EVENT_FMT = '<IIHHi16s'",
        "",
        "# parameter set: (name, type, default, min, max); order == C struct order",
        "PARAMS = (",
    ]
    for name, typ, d, lo, hi in params:
        lines.append(f"    ({name!r}, {typ!r}, {d!r}, {lo!r}, {hi!r}),")
    lines += [
        ")",
        "PARAM_FMT = '<' + ''.join('f' if p[1] == 'F' else 'i' for p in PARAMS)",
        "PARAM_COUNT = len(PARAMS)",
        "PARAM_BLK_FMT = '<4I' + PARAM_FMT[1:]      # seq, crc, version, size, params",
        "ECHO_FMT = '<4I' + PARAM_FMT[1:]           # seq, applied_count, last_result, applied_seq, params",
        "",
        "assert struct.calcsize(HDR_FMT) == 64",
        "assert struct.calcsize(STATUS_FMT) == 64",
        "assert struct.calcsize(TELEM_FMT) == 64",
        "assert struct.calcsize(EVENT_FMT) == 32",
        "",
        "# event-ring types (BC_EVT_LOG_*)",
        "EVT_LOG_STATE, EVT_LOG_CMD, EVT_LOG_PARAMS, EVT_LOG_CALIB, EVT_LOG_TIMING, EVT_LOG_PONG = 1, 2, 3, 4, 5, 6",
        "",
        "# mailbox protocol (bc_proto.h)",
    ]
    for k, v in proto:
        lines.append(f"{k} = {v}")
    lines += [
        "",
        "STATE_NAMES = ('BOOT', 'CALIBRATING', 'IDLE', 'ARMING', 'BALANCING', 'FALLEN', 'FAULT', 'ESTOP')",
        "FAULT_NAMES = ('NONE', 'FALL', 'LIFT', 'IMU_BUS', 'IMU_STUCK', 'IMU_RANGE', 'SATURATION', 'TIMING',",
        "               'ESTOP', 'PARAM', 'IMU_INIT', 'CALIB')",
        "",
    ]
    text = "\n".join(lines)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit(f"{OUT} is out of date: run {Path(__file__).name}")
        print("bc_layout.py is up to date")
        return
    OUT.write_text(text)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
